language: php

php:
  - 7.0
  - 5.6

before_install:
  - pecl install xdebug
  - phpenv rehash
  - wget https://scrutinizer-ci.com/ocular.phar

before_script:
  - composer selfupdate

script:
  - composer install
  - vendor/bin/robo run:tests
  - vendor/bin/robo run:cs
  - vendor/bin/robo run:cpd
  - vendor/bin/robo run:md
  - php ocular.phar code-coverage:upload --format=php-clover $TRAVIS_BUILD_DIR/target/reports/unit/clover.xml

notifications:
  email: t.wagner@techdivision.com
  email: b.wick@techdivision.com
